### ISSUE TITLE
gaining XP via iguana tweaks

### ISSUE THREAD

**Issue by belathus** [Lance5057/Tinkers-Defense#10]
There doesn't seem to be a way to gain xp via iguana tweaks. I tried a shield bash, blocking, or punching mobs with it in my hand. I realize there isn't much currently in the way of modifiers, but it'd be nice to have when there are more modifiers available.

**Comment by vagaprime** [comment]
I have messaged Boni about being able to remove armor type tcon items from the tweaks debuff.

**Comment by Lance5057** [comment]
This isn't going to happen due to TiCo2 and the lack of a new iguana teaks.
