### ISSUE TITLE
Queen's Gold item id contains spaces and an apostroph

### ISSUE THREAD

**Issue by kutschkem** [Lance5057/Tinkers-Defense#11]
I am trying to use MineTweaker with Tinkers-Defense, but it doesn't work because Queen's Gold Ingot has an id with spaces and an apostroph, and MineTweaker doesn't like that atm. I realize this is a problem/bug with MineTweaker, not Tinkers-Defense, but my personal opinion is that it would be better style if the id was queensGoldIngot. While you are at it, look at the other ids, too (I only saw that with Queen's gold, but haven't checked the rest)

**Comment by Dream-Master** [comment]
@Lance5057 
This change is not in Version 1.2.1.
Is the alpha version stable enough to use or can you add a new Stable version with this changes ?
Tanks.

**Comment by Dream-Master** [comment]
Ok i make me a own custom version 1.2.1a Mineteaker compatible version of your Mod.
