### ISSUE TITLE
Not an Issue more of a question.

### ISSUE THREAD

**Issue by lilmoefow** [Lance5057/Tinkers-Defense#12]
Is there no support for the newest version of ExtaTIC for this mod??  i see on the extratic minecraft forum that its on your end to make it compatible and then i see on your curse page that its on their end to make it compatible...  Just figured id ask here and get a definitive answer.  Sorry if I'm being a bother.

**Comment by Lance5057** [comment]
Do you have a link to the extratic post that says its on my end?

**Comment by lilmoefow** [comment]
its an old post (and i dont think its by any actual devs, just a bunch of users arguing)


User The_Kakuzato's Question and InkDragon's answer is on this page closer to the bottom
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/1445212-extratic-tinkers-construct-mod-support-add-on?page=49 

The posts are from February, but its the only info i can find on them not working together..
