### ISSUE TITLE
Chain Shirt and Plate Leggings - Incorrectly Named

### ISSUE THREAD

**Issue by murapix** [Lance5057/Tinkers-Defense#14]
I saw the /r/feedthebeast post you made about the armor, and so far, I have to say that it is looking great! However, the chain shirt and plate leggings are named incorrectly in the imgur album.

You called the chain shirt a halberd, but a halberd is a polearm - basically an axe on the end of a staff. Chain shirts are generally called hauberks.

As for the plate leggings, you got it almost right. They aren't called grieves, but greaves. Small difference, but the first is a verb, while the other is lower leg plates.

Sorry if this comes across as condescending. It just pains me to see these terms misused, especially as someone who has been training to use medieval weapons and armor for several years now.

**Comment by Lance5057** [comment]
Yea at some point I goofed up the name and it never occurred to me that it was wrong. I'll fix it in the next release.
