### ISSUE TITLE
Cannot run w/o Botania, BuildCraft (also some other issues / suggestions)

### ISSUE THREAD

**Issue by gamrguy** [Lance5057/Tinkers-Defense#17]
Exactly what it says. Code is trying to access Botania / BC elements while they are not present. Specifically:

core.tools.modifiers.ActiveToolMods.TDefenseActiveToolMod (tries to create a BotaniaToolMods object where there is no Botania installed)
core.tools.TinkerWrench (extends IToolWrench from the BC API)

These results were gained from the deobf environment. EDIT: Results are the same in a regular environment as well.

Also, the mod will not compile without Botania because of the import attempt, which doesn't seem right IMHO.

One final thing: how in the world did you get Battlegear 2 to work in the dev environment??? Everything I've done gives me a weird crash on entering the world that looks like this:
> java.lang.IllegalAccessError: tried to access method net.minecraft.entity.EntityLivingBase.getArmSwingAnimationEnd()I from class net.minecraft.entity.player.EntityPlayer

EDIT: Figured I'd like to point out a few more issues with the current code, rather than make another issue statement (also suggestions, general "thing X that is unfinished doesn't work yet even though there is no real point in saying that because unfinished", etc):
-Many texture paths are typed incorrectly (case MATTERS), one case even has "textures/items/textures/armor/ChainArmor.png" which isn't even a real directory
-Armor rendering for helmet and boots are wayyyy off (at least for normal armor). I get that armor is very new and unfinished (to the point that you are literally invincible with a chestplate, the pieces have attack damage, you can put weapon modifiers on them, they call themselves broken (and give a broken 'broken' texture) even though it still has durability...) but maybe get this done first? :)
-Crests don't show up on shields.
-(suggestion) Zweihander is a cheap Terra Blade?? What?!??! Doesn't even use mana! I rate this weapon as a cheap and broken version of a cleaver, doing -1 damage for: free (though weak) ranged attack that requires Botania to be installed and no swing speed debuff. Looks very cool though, I would suggest a rework of the weapon. However, there are no Zweihanders in Battlegear (the mod this mod was intended to bridge TConstruct with) so it seems out of place. Same with the Wrench and Shears. Perhaps split that off as its own mod, and put things like Maces and Waraxes in this one.
-I think armor should be split off at some point as well. Some people might want the armor, but not Battlegear.

Finally I'll say that I don't know what you're thinking, I don't know what stuff is on the top of your to-do list and why, and I do know that it's likely you already know most of the stuff that I just said. So this is just me commenting on that. Don't take it badly :)

**Comment by Lance5057** [comment]
I'm guessing you built your own jar from the code, I'll warn against doing this cause I have a habit of leaving bugs or tests in it.
Getting the MnB api to work was basically black magic, I'm not 100% sure how I got it to work...
I refactored a lot of the item names so things are a bit goofy.
Crests aren't finished yet.
The terrablade thing was a test, all TiCo tools would shoot terra beams just to see if I could do so.
This mod is slowly pulling away from MnB, I'm adding many more things that have nothing to do with it and in 1.9 it'll have no involvement at all.
