### ISSUE TITLE
Heavy armor issues

### ISSUE THREAD

**Issue by mailleseraph** [Lance5057/Tinkers-Defense#18]
Heavy armor has a couple problems.
1) durability drops super fast, like 50 points a hit
2) armor switches to "broken" after one hit, (labeled as broken and with broken texture, which has the broken item texture over missing texture purple and black squares, this was using bronze and iron parts, so you may be missing part of those textures)
3) players don't take damage in heavy armor, I sat in heavy armor boots getting knocked around by thaumcraft cultists and didn't take any damage.

most of these sound like debug features that didn't get disabled.

**Comment by Lance5057** [comment]
This has been fixed.
