### ISSUE TITLE
[TCon API] Material ID 201 is already occupied by AeonSteel

### ISSUE THREAD

**Issue by lightning02** [Lance5057/Tinkers-Defense#19]
https://github.com/SlimeKnights/TinkersConstruct/issues/2086

**Comment by Lance5057** [comment]
Update to 1.3.4a, its an alpha but it's stable. It adds a config file to change material ID's so this doesn't happen.

**Comment by lightning02** [comment]
Oh, nice! But..Where can i download that version? :/

**Comment by lightning02** [comment]
Yeah, you've right! The problem is fixed, thanks!! :)

**Comment by SvEgiiVEteR** [comment]
I also on 1.3.7
and how do you know occupied by Material ID ?
