### ISSUE TITLE
Chainmail Form wrong meta id for Tinkers defence Materials

### ISSUE THREAD

**Issue by Dream-Master** [Lance5057/Tinkers-Defense#22]
Screenshoot explain all. Meta id must be 4 not 3
![image](https://cloud.githubusercontent.com/assets/2970688/17375123/07082c32-59b0-11e6-8dd4-af72a122e814.png)

![image](https://cloud.githubusercontent.com/assets/2970688/17375132/0d717948-59b0-11e6-86d5-5a501a7f3e48.png)

Tinkers defense 1.3.6

**Comment by Lance5057** [comment]
Thanks, not sure how I managed to overlook that one.
