### ISSUE TITLE
Thaumium tool parts not shown

### ISSUE THREAD

**Issue by Dream-Master** [Lance5057/Tinkers-Defense#23]
![image](https://cloud.githubusercontent.com/assets/2970688/17375274/8a37fcfe-59b0-11e6-8f0c-59cd4423e21a.png)
![image](https://cloud.githubusercontent.com/assets/2970688/17375281/8e8fdd80-59b0-11e6-87d2-08b1abfbf841.png)
![image](https://cloud.githubusercontent.com/assets/2970688/17375285/92fd2a9e-59b0-11e6-8c7b-6df75eeb9445.png)
![image](https://cloud.githubusercontent.com/assets/2970688/17375286/97908cc2-59b0-11e6-8e4f-28cf45554835.png)

**Comment by Dream-Master** [comment]
Ok have to test if this is disabled with Tinkers Gregworks.

**Comment by Dream-Master** [comment]
No not worked.

**Comment by Lance5057** [comment]
See #21 , it's an odd one.
