### ISSUE TITLE
[Bug]Transparent Armor

### ISSUE THREAD

**Issue by AsmodeiXIII** [Lance5057/Tinkers-Defense#24]
For Some reason, armors from this mod have this effect all the time: http://imgur.com/a/0O2VD
Happens even without fastcraft
Modlist: http://imgur.com/a/NkcXV
Any info i can give, just ask.

**Comment by Lance5057** [comment]
Are you using optifine?

**Comment by AsmodeiXIII** [comment]
No, i am not.

2016-08-04 10:14 GMT-04:00 Lance5057 <notifications@github.com>:

> Are you using optifine?

**Comment by Lance5057** [comment]
Try the command "/TD toggle transparency"

**Comment by AsmodeiXIII** [comment]
That solved it, thanks! No idea why was that on in the first place.

2016-08-04 10:21 GMT-04:00 Lance5057 <notifications@github.com>:

> Try the command "/TD toggle transparency"

**Comment by Lance5057** [comment]
That was there for the goggles of revealing modifier before it was
scrapped, not sure why it made all the armor transparent though
