### ISSUE TITLE
[Crash] Opening a Chest with bow in it.

### ISSUE THREAD

**Issue by AsmodeiXIII** [Lance5057/Tinkers-Defense#25]
Opening a chest with my bow (a slime+firestring bow with fortune) causes a crash: 
http://pastebin.com/uxNVF1XB

The bow was made prior to installing your mod.

Also, i dont know if its relevant but im using iguana tweaks and extratic

**Comment by Lance5057** [comment]
Did you happen to put this into the finishing anvil, I'm not really sure about the cause of this one.

**Comment by AsmodeiXIII** [comment]
Not at all, the moment i installed your mod i could not open the chest that
contained my bow. Uninstalling your mod and moving the bow changed the
crashing chest (once i reinstalled the mod, obv) so it isn't a problem with
this particular chest (that i know of).

2016-08-14 2:09 GMT-04:00 Lance5057 <notifications@github.com>:
