### ISSUE TITLE
Crash with Stencil Table and TD Stencils

### ISSUE THREAD

**Issue by xeronut** [Lance5057/Tinkers-Defense#26]
http://pastebin.com/7wV8L079

Using TiC Tooltips and Iguana Tinker Tweaks.  Crash occurs when I open the Stencil Table, select one of the new stencils, exit table, then try and reopen the Stencil table.  Crash does not occur with vanilla TCon parts already selected, only the 5 from TD.

**Comment by Lance5057** [comment]
This is fixed, it sometimes swaps between my patterns and the ranged patterns when reopening but it shouldn't crash anymore.
