### ISSUE TITLE
Crash when upgrading equipment parts in Tool Forge

### ISSUE THREAD

**Issue by xeronut** [Lance5057/Tinkers-Defense#27]
http://pastebin.com/hZ0EChke

Using both TiC Tooltips and Iguana Tinker Tweaks.  Crash occurred when I tried to put a substitute Armor Plate into the Tool Forge to replace one of the Armor Plates in a Heater Shield I made, instant crash.  For reference, shield was made of Bronze Tough Rod, Alumite Armor Plate, Steel Armor Plate and an Electrum Rivet, and I tried swapping in an Iron Armor Plate to test functionality.  Upon reloading the world the Iron Armor Plate is gone and the Heater Shield I had made was intact, still in the Tool Forge.

**Comment by Lance5057** [comment]
Fixed, see #21.
