### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Dream-Master** [Lance5057/Tinkers-Defense#29]
Here the crash Log:

https://gist.github.com/Dream-Master/f21143b5efbc2538a10e300239352ece

Old Version 1.2.1 works fine.

Thermos 1614 Build 56 
used in a Modpack
https://github.com/GTNewHorizons/NewHorizons

**Comment by Lance5057** [comment]
This has been fixed. A release will be out shortly.

**Comment by Dream-Master** [comment]
OK nice.

**Comment by Go-Wish** [comment]
I am having the same problem on the new version.

**Comment by Dream-Master** [comment]
@Go-Wish Yes sadly the new versions are very buggy too. Have a lot of issues with t and backdate to 1.2.1.
