### ISSUE TITLE
[Bug] Crash while repairing Steel Armor

### ISSUE THREAD

**Issue by AsmodeiXIII** [Lance5057/Tinkers-Defense#30]
http://pastebin.com/6kmLKZ7B

The crash report mentions something about the vis repair modifier, however i was trying to repair steel armor (the toolforge one, forgot the name), the armor had no modifiers whatsoever.

Any other info i can provide let me know.

**Comment by AsmodeiXIII** [comment]
Another one, this time trying to modify the armor with a manasteel core: http://pastebin.com/cvbxASv6

**Comment by Lance5057** [comment]
This was an issue caused by Thaumic Horizons and my mod. See #21 for more info.
