### ISSUE TITLE
Extreme lag while looking at another player in tinkers defense armor 

### ISSUE THREAD

**Issue by void6425** [Lance5057/Tinkers-Defense#32]
Hi i am currently playing on a server with another player when i look at there player model while they are wearing your armor my fps tanks from 120 to 14 as soon as they take it off im back up to 120. We are currently on 1.3.4a. This  is an outdated version but I was Just letting you know about this bug. (we are not on the newest version because the pack has not got your new version)

**Comment by Lance5057** [comment]
This has been fixed, the armor was rendering 16x per piece.
