### ISSUE TITLE
Tinker's Glove crashing game.

### ISSUE THREAD

**Issue by TheIvanic** [Lance5057/Tinkers-Defense#34]
Attempting to add a modifier to the Tinker's Glove Item causes a crash:
[http://pastebin.com/AgdLTkzT](http://pastebin.com/AgdLTkzT)

When I disabled TD my client stopped crashing, so this would seem to confirm TD as the cause.   Hope you can find and fix the issue in time to roll it into your next update.  Until then I'll just keep the Tinker's glove recipe disabled.

**Comment by vagaprime** [comment]
I am getting similar crash but when I put the tinkers goggles into a tool forge.
