### ISSUE TITLE
Registering texture java.nio.file.FileSystemNotFoundException

### ISSUE THREAD

**Issue by Dream-Master** [Lance5057/Tinkers-Defense#36]
Hi i getting this problem with 1.3.7 newest Version

https://gist.github.com/Dream-Master/ae3078e09f1f6c738807c932ed89f972

maybe something wrong with texture packing?

**Comment by Dream-Master** [comment]
Redownload it now it works. Will make more tests to be sure.

**Comment by Lance5057** [comment]
So this is kinda a weird thing I hope to make work better later but atm my
jar cannot be renamed or it won't load. This is due to the finishing anvil
extracting image filenames from my jar dynamically and atm I can't figure
out a better way to do it.

**Comment by Dream-Master** [comment]
Ah ok thats maybe was it. Ok maybe possible in your next version ?
