### ISSUE TITLE
Crash when be in The finishin Anvil Gui and try to get Schield item via nei

### ISSUE THREAD

**Issue by Dream-Master** [Lance5057/Tinkers-Defense#37]
Crash Log

https://gist.github.com/Dream-Master/d3472bee80fa3586c93bbbba90fb272d

My Modpack:

https://github.com/GTNewHorizons/NewHorizons

MC 1.7.10
Forge 1614
Tinkers Defense 1.3.7

And Mopack

**Comment by Lance5057** [comment]
I'm not sure what exactly is causing this so it's gonna have to be a "don't do that" for now.

**Comment by jandrewsfm** [comment]
line 516 of Gui_FinishingAnvil.java is missing a null check. Just change it to `(bigCopy != null && (rest of line here)`

**Comment by Dream-Master** [comment]
Ok will try it thanks.

**Comment by nvrsbr** [comment]
> line 516 of Gui_FinishingAnvil.java is missing a null check. Just change it to `(bigCopy != null && (rest of line here)`

I have zero clue how to do this. I would love to get this fixed, any help would be greatly appreciated.
I know its a long shot for something so old but I have had this mod in my 1.7.10 Modpack for a LONG time and would like to get this bug fixed if possible.

(tinkersdefense-1.3.7.jar)

**Comment by nvrsbr** [comment]
> I'm not sure what exactly is causing this so it's gonna have to be a "don't do that" for now.

There seems to be a fix for this issue posted by **jandrewfsm** above.
Does this work and what exactly does line 516 need to look like after the edit?
Currently it looks like this:
**if (this.bigCopy.func_77973_b() instanceof ArmorCore) {**

**Comment by nvrsbr** [comment]
> Ok will try it thanks.

Did you ever try the fix and did it work?
Any chance you can tell me exactly what you did?

**Comment by Lance5057** [comment]
Please stop posting in closed issues.
