### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by vrork** [Lance5057/Tinkers-Defense#38]
https://gist.github.com/vrork/adb4d52a32623097a81198a29c9edd36

**Comment by lilmoefow** [comment]
downgrade your tinkers back to TConstruct-1.10.2-2.5.6b.jar for now.  Tinkers defense has not updated to the new versions of Tconstruct yet I assume.

**Comment by vrork** [comment]
@lilmoefow nope, not gonna do it, Bows were added!

**Comment by Dream-Master** [comment]
Tinkers Defence not working on a 1.7.10 version anymore.

**Comment by vrork** [comment]
And who said it is 1.7.10? Its 1.10.2

**Comment by lilmoefow** [comment]
Yes I know bows were added in that version. The API was also changed in that version meaning that Tinkers Defense for 1.10.2 will not be compatible with that update just yet.  Give it a bit for a reply from the dev, and for now just downgrade if you want to be able to actually launch/play what ever pack you are working with.
