### ISSUE TITLE
Glowstep Suggestion.

### ISSUE THREAD

**Issue by vagaprime** [Lance5057/Tinkers-Defense#40]
With the glowstep modifer as it is now it kinda spams the glow shards around like crazy. Would there be a way to have the glowstep require a specific light like say 7. I know that tinkers for 1.10.2 has a modifer for tools right now that places a glow orb when you hit light level 7.

**Comment by Lance5057** [comment]
I believe I had it set to every 8 steps but having it check the light level would be a possibility.

**Comment by vagaprime** [comment]
Ya its set to every 8 steps, and that leads to a bit of spam of glow crumbs when you are taking the same route over and over again. I have had crumbs get placed like 2 blocks apart.
