### ISSUE TITLE
Update your mod

### ISSUE THREAD

**Issue by vrork** [Lance5057/Tinkers-Defense#45]
Just please, update your mod for the latest TC version

**Comment by Lance5057** [comment]
The issue tracker is not for bugging me about updating, I'll update it when I update it. This mod is just a hobby of mine so it's not high on my priority list and being annoying about when I update it isn't going to make me want to update it any faster.

**Comment by chimericdream** [comment]
@Lance5057 I know you haven't asked for it, but I'd be willing to pitch in some time to help update the mod. Though I am fairly new to writing MC mods, I have been writing code for most of my life and have spent the last ~10 years as a software developer. Like you, I don't have large quantities of spare time, but I enjoy contributing to projects I have a vested interest in.

Either way, I'm looking forward to using TD when it's updated for compatibility with the latest TiC and hope you are able to set aside time (sanity and real life permitting) to update!

**Comment by Lance5057** [comment]
I'm completely open to pull requests, by all means.
I'm not sure why the latest code isn't up, I swear I had pushed it. I'll look and let you know.
