### ISSUE TITLE
Github isn't taking the updates

### ISSUE THREAD

**Issue by Lance5057** [Lance5057/Tinkers-Defense#46]
Putting this here for anyone wondering why my github hasn't updated in 6 months. For some reason I've submitted several pushes and none of them are going through, I'll be attempting to fix this but until then I have no idea what the issue is.

**Comment by yotthani** [comment]
Any update here ? had to take out your great mod out my pack because i got crashes on the tinkers gear and the finishing anvil

**Comment by Lance5057** [comment]
Seems to finally be fixed.
