### ISSUE TITLE
Missing gradlew wrapper

### ISSUE THREAD

**Issue by Midnightfender** [Lance5057/Tinkers-Defense#47]
Went to build this and realized you were missing the gradlew wrapper. Also what version of java was this built on? IIRC eclipse said 6?

**Comment by superninjakiwi** [comment]
I can verify that building doesn't work properly right now, I had the same issue when I tried to build it.

**Comment by Midnightfender** [comment]
I installed a local version of  gradlew and got eclipse all set but there was a numerous amounts of errors but thats not for here.

**Comment by Lance5057** [comment]
I've added a gradle wrapper that downloads all dependencies.
