### ISSUE TITLE
Possible new additions?

### ISSUE THREAD

**Issue by Xanderill** [Lance5057/Tinkers-Defense#5]
So I was thinking about this mod and what possibly could be coming in the future. Of course, Heraldry came to mind; But what about armor? Mine and blade: Battlegear is required for this mod to run, and it has knightly armor which isn't quite implemented yet, understandably. Tinkers' Construct really only adds the travelers' gear which isn't very armor-like. So why not add different types of armor? From mail to banded, to half plate, to full-plate to everything in between! All of which available with the tinkers' construct metals! Imagine Bronze-studded Leather, or wooden chain armor! My ideas go deeper than this as well, I have a full range of possible modifiers or the ability to add parts to your armor like a faceplate for your helmet, of Pauldrons to your chest armor. How would you go about doing this? Easy. A new crafting station: The armor Crafting Table. This would also have to including new casts for the new parts required to make the armor, all of which I can design. The possibilities are endless, and I have a full list of items and designs I can't wait to explain to you! Private message me If you like the idea and wish to talk about adding anything!

**Comment by Lance5057** [comment]
Almost all of this is actually in the plans. I've even been working on models of armor that can be found in the techne models folder. Armor is next on the list after I finish the Crest Mount but I'm having some programming troubles atm.

**Comment by Xanderill** [comment]
i would love to help with models and textures if you're up for accepting the help

**Comment by Lance5057** [comment]
You're welcome to submit, if we like it we'll merge it in.
