### ISSUE TITLE
crash with tinkersplus and moartinkers

### ISSUE THREAD

**Issue by Hypsellis** [Lance5057/Tinkers-Defense#52]
Tinkers Defense registers its materials without checking if it has been already registered by another mod, and there is no way to disable some materials, so it crashes. https://pastebin.com/jjCzEwPV

**Comment by AugiteSoul** [comment]
Disable platinum in Moar Tinkers.

**Comment by Hypsellis** [comment]
I would have to disable all the ores which are twice used by MoarTinker and PlusTic and your mod, while I would want to keep their material version.
Anyway the problem come from your mod, it's you who register twice an ore which has been already registered, while MoarTinker and PlusTic both check if the material are already registered before to register them for preventing crash, and all the materials can be disabled, while yours not.

**Comment by SHIuSH** [comment]
if anyone figured, can someone list materials that overlap between moartinkers and tinkers defense?

**Comment by Lance5057** [comment]
I've added a material blacklist for this issue.
