### ISSUE TITLE
[1.12.2] Issues & Suggestions

### ISSUE THREAD

**Issue by Preminenc3** [Lance5057/Tinkers-Defense#54]
Problems:

- Both shields do not work and the shield animation does not work. 
- Necklace can't be placed in baubles necklace slot but it can be placed in the ring slot.
- Cloth stencil does not work, and the stencil cloth icon is hard to see the stencil.
- None of the armor is wearable.
- Armor plate item is not being read in as a part of the tool forge for the shawl and the boots, so you can not craft those items.
- Fishing rod does not work.
- Tinkers added a new tool that basically does what shears do but more so the shears are not really needed, but they work just fine.
- Problem with item ID's everything is coming out as Example: item.zweihander.name and the desc in the tool forge is item.zweihander.desc

Suggestion:
Making the armor out of cloth doesn't make much such and steers away from the purpose of tinkers being custom items using metals. If you can come up with an alternative for cloth I think it would make the mod more "friendly". You don't have to come up with an alternate item you can always use the ones you already made.

**Comment by Lance5057** [comment]
Most of these things are being worked on. Generally if the jar has an a at the end of it, it means its not going to be as pretty as a normal release.
