### ISSUE TITLE
Crash on server

### ISSUE THREAD

**Issue by lebanni** [Lance5057/Tinkers-Defense#55]
MC 1.12.2
tinkersdefense-1.4.2.4a.jar
TConstruct-1.12.2-2.9.0.55.jar

https://gist.github.com/lebanni/e8b7c8accc7285f51b7b20166955a778
https://gist.github.com/lebanni/0d58a52ae9c974622ee1b75070a2dd89

**Comment by Lance5057** [comment]
Neither of those links work...

**Comment by lebanni** [comment]
Corrected.

**Comment by kreezxil** [comment]
The latest version of this mod is December 4, 2017. Can please post an update. I was about to post a duplicate of this bug today.

**Comment by Lance5057** [comment]
I generally release alpha builds on my discord and not on curse if you want.
