### ISSUE TITLE
Tinkers ingots not reversable

### ISSUE THREAD

**Issue by BakermanLP** [Lance5057/Tinkers-Defense#6]
Hello,
We tried to cast some ingots out of liquid aeon steel. That worked so far, but these can't be smelted again. The ingots have the ID 6534:9, but the normal ingots have only 6534. Is this a bug?

**Comment by Lance5057** [comment]
This has been fixed in the 1.1 update. Make sure you download the newest one from the forum, the curse widget is being finicky and only gives 1.0.

**Comment by Grambosch** [comment]
Fixes the 1.1 also not being able to repair eg my Aeon Lumber Axe with Aeon Steel?

**Comment by Lance5057** [comment]
Yes that should also be fixed
