### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by nathanlevy153** [Lance5057/Tinkers-Defense#60]
Here it is
---- Minecraft Crash Report ----
// Don't do that.

Time: 3/11/18 7:18 PM
Description: Registering texture

java.nio.file.FileSystemNotFoundException: C:\Users\Jones\AppData\Roaming\.minecraft\mods\tinkersdefense-1.3.6.jar
	at com.sun.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:120)
	at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:139)
	at java.nio.file.FileSystems.newFileSystem(Unknown Source)
	at lance5057.tDefense.finishingAnvil.utilities.Injector.loadHeads(Injector.java:59)
	at lance5057.tDefense.finishingAnvil.utilities.Injector.func_94581_a(Injector.java:240)
	at net.minecraft.client.renderer.texture.TextureMap.func_110573_f(TextureMap.java:524)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:171)
	at net.minecraft.client.renderer.texture.TextureMap.func_110551_a(TextureMap.java:152)
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:101)
	at net.minecraft.client.renderer.texture.TextureManager.func_110549_a(TextureManager.java:215)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:143)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:617)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:327)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.sun.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:120)
	at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:139)
	at java.nio.file.FileSystems.newFileSystem(Unknown Source)
	at lance5057.tDefense.finishingAnvil.utilities.Injector.loadHeads(Injector.java:59)
	at lance5057.tDefense.finishingAnvil.utilities.Injector.func_94581_a(Injector.java:240)
	at net.minecraft.client.renderer.texture.TextureMap.func_110573_f(TextureMap.java:524)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:171)
	at net.minecraft.client.renderer.texture.TextureMap.func_110551_a(TextureMap.java:152)

-- Resource location being registered --
Details:
	Resource location: minecraft:textures/atlas/items.png
	Texture object class: net.minecraft.client.renderer.texture.TextureMap
Stacktrace:
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:101)
	at net.minecraft.client.renderer.texture.TextureManager.func_110549_a(TextureManager.java:215)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:143)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:617)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:327)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 256307640 bytes (244 MB) / 1456275456 bytes (1388 MB) up to 1593180160 bytes (1519 MB)
	JVM Flags: 8 total; -XX:+UseConcMarkSweepGC -XX:-UseAdaptiveSizePolicy -XX:+CMSParallelRemarkEnabled -XX:+ParallelRefProcEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseCMSInitiatingOccupancyOnly -Xmx1536M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_E3 117 mods loaded, 117 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJA	ImmibisMicroblocks{59.0.5} [Immibis's Microblocks] (immibis-microblocks-59.0.5.jar) 
	UCHIJA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJA	se{0.4.1} [Super Enchants] (minecraft.jar) 
	UCHIJA	OpenModsCore{0.10} [OpenModsCore] (minecraft.jar) 
	UCHIJA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJA	battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.8.3.jar) 
	UCHIJA	llibrary{0.3.3} [LLibrary] (LLibrary-0.3.3-1.7.10.jar) 
	UCHIJA	mowziesmobs{1.2.5-undefined} [Mowzie's Mobs] (123.Mowzie's Mobs-1.2.5.jar) 
	UCHIJA	walljump{1.2.1c} [WallJump] ([1.7.10] [Forge] Wall Jump 1.2.1c by NukeDuck.zip) 
	UCHIJA	securitycraft{v1.8.2} [SecurityCraft] ([1.7.10] SecurityCraft v1.8.2.jar) 
	UCHIJA	RandomThings{2.1.1} [Random Things] (_Random-Things-Mod-1.7.10.jar) 
	UCHIJA	adventurebackpack{1.7.10-0.8b} [Adventure Backpack] (adventurebackpack-1.7.10-0.8c.jar) 
	UCHIJA	animalbikes{1.7.10} [Animal Bikes] (Animal-Bikes-Mod-1.7.10.jar) 
	UCHIJA	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
	UCHIJA	armourersWorkshop{1.7.10-0.40.1} [Armourer's Workshop] (Armourers-Workshop-1.7.10-0.40.1.jar) 
	UCHIJA	plushieWrapper{0.0.0} [Plushie Wrapper] (Armourers-Workshop-1.7.10-0.40.1.jar) 
	UCHIJA	chocolateQuest{1.0} [Chocolate Quest] (Better-Dungeons-Mod-1.7.10.jar) 
	UCHIJA	betterloadingscreen{1.3.2} [Better Loading Screen] (Better-Loading-Screen-Mod-1.7.10.jar) 
	UCHIJA	BiblioCraft{1.11.5} [BiblioCraft] (BiblioCraft-Mod-1.7.10.jar) 
	UCHIJA	BiblioWoodsNatura{1.5} [BiblioWoods Natura Edition] (BiblioWoods-Natura-Edition-Mod-1.7.10.jar) 
	UCHIJA	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1826-universal.jar) 
	UCHIJA	bookshelf{1.0.4.172} [Bookshelf] (Bookshelf-1.7.10-1.0.4.172.jar) 
	UCHIJA	BrickaBrac{1.7.10-1.1.0b} [Brick-a-Brac] (Brick-a-Brac-Mod-1.7.10.jar) 
	UCHIJA	PreciousBricks{1.7.10-1.0.0b} [Precious Bricks] (Brick-a-Brac-Mod-1.7.10.jar) 
	UCHIJA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJA	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
	UCHIJA	chisel{2.9.5.11} [Chisel] (Chisel-2.9.5.11.jar) 
	UCHIJA	CarpentersBlocks{3.3.8.1} [Carpenter's Blocks] (Carpenter's Blocks v3.3.8.1 - MC 1.7.10.jar) 
	UCHIJA	CoFHCore{1.7.10R3.1.4} [CoFH Core] (CoFHCore-[1.7.10]3.1.4-329.jar) 
	UCHIJA	colorfularmor{1.7.10-2.7} [Colorful Armor] (Colorful-Armor-Mod-1.7.10.jar) 
	UCHIJA	colourfulportalsmod{1.4.3} [Colourful Portals] (ColourfulPortals-1.4.3.jar) 
	UCHIJA	SC0_SpaceCore{0.7.14} [SpaceCore] (SpaceCore-1.7.10.jar) 
	UCHIJA	ThermalFoundation{1.7.10R1.2.6} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.6-118.jar) 
	UCHIJA	ThermalExpansion{1.7.10R4.1.5} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.5-248.jar) 
	UCHIJA	SC0_ComponentEquipment{0.17.4} [Component Equipment] (Component-Equipment-Mod-1.7.10.jar) 
	UCHIJA	craftingpillars{1.6.0} [Crafting Pillars Mod] (CraftingPillars-1.7.x-1.6.1.jar) 
	UCHIJA	custom_sword{1.7.2} [Custom Sword  By Kelco_K22] (Custom-Sword-Mod-1.7.10.jar) 
	UCHIJA	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_mod-1.7.10d.jar) 
	UCHIJA	D3Core{1.1.2.41} [D3Core] (D3Core-1.7.10.jar) 
	UCHIJA	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.3.3_1.7.10.jar) 
	UCHIJA	props{2.3.3} [Decocraft] (Decocraft-2.3.3_1.7.10.jar) 
	UCHIJA	DescriptionTags{1.0} [Description Tags] (DescriptionTags-1.0-1.7.10.jar) 
	UCHIJA	doorsoplenty{0.1} [Doors O' Plenty] (Doors-O-Plenty-Mod-1.7.10.jar) 
	UCHIJA	DragonMounts{r41-1.7.10} [Dragon Mounts] (Dragon-Mounts-Mod-1.7.10.jar) 
	UCHIJA	DynamicLights{1.3.9a} [Dynamic Lights] (Dynamic-Lights-Mod-1.7.10.jar) 
	UCHIJA	SlimevoidLib{2.0.4.7} [Slimevoid Library] (SlimevoidLibrary-2.0.4.7.jar) 
	UCHIJA	DynamicTransport{0.1.2.0} [Dynamic Transport] (Dynamic-Transport-Mod-1.7.10.jar) 
	UCHIJA	tntland{1.0} [Elemental-Power] (Elemental-Power-[1.7.10]-1.4.jar) 
	UCHIJA	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) 
	UCHIJA	endercore{1.7.10-0.2.0.39_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.39_beta.jar) 
	UCHIJA	EnderIO{1.7.10-2.3.0.429_beta} [Ender IO] (EnderIO-1.7.10-2.3.0.429_beta.jar) 
	UCHIJA	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
	UCHIJA	farlanders{1.2b} [The Farlanders] (Farlanders-Mod-1.7.10.jar) 
	UCHIJA	FoodPlus{3.2rS} [§bFood Plus] (FoodPlus-1.7.2-3.2rS.jar) 
	UCHIJA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJA	grapplemod{1.7.10-v8} [Grappling hook mod] (grapplemod-1.7.10-v8.jar) 
	UCHIJA	GrimoireOfGaia{1.0.0} [Grimoire of Gaia 3] (GrimoireOfGaia3-1.7.10-1.1.2.jar) 
	UCHIJA	HardcoreEnderExpansion{1.8.4} [Hardcore Ender Expansion] (HardcoreEnderExpansion  MC-1.7.10  v1.8.4.jar) 
	UCHIJA	hgp{Release} [Horizontal Glass Panes] (Horizontal-Glass-Panes-Mod-1.7.10.jar) 
	UCHIJA	iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2.jar) 
	UCHIJA	ImmibisCore{59.1.4} [Immibis Core] (immibis-core-59.1.4.jar) 
	UCHIJA	InfernalMobs{1.6.6} [Infernal Mobs] (InfernalMobs-1.7.10.jar) 
	UCHIJA	IronChest{6.0.60.741} [Iron Chest] (Iron-Chests-Mod-1.7.10.jar) 
	UCHIJA	ism{1.5.9 MC-1.7.10} [Instant Structures Mod (ISM)] (ism-1.5.9 MC-1.7.10.jar) 
	UCHIJA	ani_koto{v1.6} [Kingdoms of the Overworld Mod] (Kingdoms-of-The-Overworld-Mod-1.7.10.jar) 
	UCHIJA	lootplusplus{0.24_for_1.7} [Loot++] (Loot-Mod-1.7.10.jar) 
	UCHIJA	lycanitesmobs{1.13.0.5 - MC 1.7.10} [Lycanites Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJA	arcticmobs{1.13.0.5 - MC 1.7.10} [Lycanites Arctic Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJA	demonmobs{1.13.0.5 - MC 1.7.10} [Lycanites Demon Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJA	desertmobs{1.13.0.5 - MC 1.7.10} [Lycanites Desert Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJA	forestmobs{1.13.0.5 - MC 1.7.10} [Lycanites Forest Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJA	freshwatermobs{1.13.0.5 - MC 1.7.10} [Lycanites Freshwater Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJA	infernomobs{1.13.0.5 - MC 1.7.10} [Lycanites Inferno Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJA	junglemobs{1.13.0.5 - MC 1.7.10} [Lycanites Jungle Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJA	mountainmobs{1.13.0.5 - MC 1.7.10} [Lycanites Mountain Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJA	plainsmobs{1.13.0.5 - MC 1.7.10} [Lycanites Plains Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJA	saltwatermobs{1.13.0.5 - MC 1.7.10} [Lycanites Saltwater Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJA	shadowmobs{1.13.0.5 - MC 1.7.10} [Lycanites Shadow Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJA	swampmobs{1.13.0.5 - MC 1.7.10} [Lycanites Swamp Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJA	malisiscore{1.7.10-0.14.3} [MalisisCore] (malisiscore-1.7.10-0.14.3.jar) 
	UCHIJA	malisisdoors{1.7.10-1.13.2} [Malisis' Doors] (malisisdoors-1.7.10-1.13.2.jar) 
	UCHIJA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJA	MetallurgyCore{4.0.5} [Metallurgy Core] (MetallurgyCore-1.7.10-4.0.5.30.jar) 
	UCHIJA	Mekanism{9.1.0} [Mekanism] (Mekanism-1.7.10-9.1.0.281.jar) 
	UCHIJA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UCHIJA	Metallurgy{4.0.6} [Metallurgy 4] (Metallurgy-1.7.10-4.0.6.80.jar) 
	UCHIJA	MoarSigns{1.0.3} [MoarSigns] (MoarSigns-1.7.2-1.0.3.jar) 
	UCHIJA	MoreBows2{1.2} [More Bows 2] (More-Bows-2-Mod-1.7.10 (1).jar) 
	UCHIJA	MorePistons{1.7.10-1.5.1.2} [More Pistons] (MorePistons-1.7.10-1.5.1.2.jar) 
	UCHIJA	Morph{0.9.2} [Morph] (Morph-Beta-0.9.2.jar) 
	UCHIJA	cfm{3.4.7} [�9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) 
	UCHIJA	NintendoSwitchMod{1.0.0} [NintendoSwitchMod] (NintendoSwitchMod_1.7.10.jar) 
	UCHIJA	notenoughIDs{1.4.3.4} [NotEnoughIDs] (NotEnoughIDs-1.7.10.jar) 
	UCHIJA	onlysilver{1.9.4-1.7.2} [OnlySilver] (OnlySilver-1.9.4-1.7.2.jar) 
	UCHIJA	OpenMods{0.10} [OpenMods] (OpenModsLib-1.7.10-0.10.jar) 
	UCHIJA	OpenBlocks{1.6} [OpenBlocks] (OpenBlocks-1.7.10-1.6.jar) 
	UCHIJA	PlaceableTools{1.2.0.33} [PlaceableTools] (Placeable-Tools-Mod-1.7.10.jar) 
	UCHIJA	placeableitems{2.0.1} [Placeable Items Mod] (placeableitems-2.0.1.jar) 
	UCHIJA	PortalGun{4.0.0-beta-6} [PortalGun] (Portal-Gun-Mod-1.7.10.jar) 
	UCHIJA	potioncore{@VERSION@} [Potion Core] (Potion-Core-1.7.10.jar) 
	UCHIJA	primitivemobs{1.0} [Primitive Mobs] (Primitive-Mobs-Mod-1.7.10.jar) 
	UCHIJA	rubymod{v0.1} [Ruby Mod] (RubyMod-[1.7.10]v0.3.jar) 
	UCHIJA	secretroomsmod{4.7.1} [The SecretRoomsMod] (secretroomsmod-1.7.10-4.7.1.413.jar) 
	UCHIJA	DP_SimpleFlight{0.8} [Simple Flight] (Simple-Flight-Mod-1.7.10.jar) 
	UCHIJA	simply_sit{1.7.10-1.1.0} [Simply Sit] (Simply-Sit-Mod-1.7.10.jar) 
	UCHIJA	StoryModeMod{1.1.1} [StoryModeMod] (StoryModeMod 1.1.1.jar) 
	UCHIJA	thecoloredblocksmod{v1.3} [thecoloredblocksmod] (TheColoredBlocksMod-v1.3-mc1.7.10.jar) 
	UCHIJA	TiCTooltips{1.2.5} [TiC Tooltips] (TiC-Tooltips-Mod-1.7.10.jar) 
	UCHIJA	tinkersdefense{1.3.6} [Tinkers' Defense] (tinkersdefense-1.3.6.jar) 
	UCHIJA	axetomahawk.core{1.4.5.2-1.7.10} [Tomahawks Core] (Tomahawk-Mod-1.7.10.jar) 
	UCHIJA	axetomahawk{1.4.5.2-1.7.10} [Tomahawks] (Tomahawk-Mod-1.7.10.jar) 
	UCHIJA	toolsdoneright{1.1.4} [Tools Done Right] (Tools Done Right by NukeDuck [1.7.10][1.1.4].zip) 
	UCHIJA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 20.19.15.4835' Renderer: 'Intel(R) HD Graphics 400'
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[player_damage_hook:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: found misbehaving transformers: me.guichaguri.betterfps.transformers.MathTransformer(me.guichaguri.betterfps.transformers.MathTransformer@3f6463ff) returned non-null result: 0,me.guichaguri.betterfps.transformers.EventTransformer(me.guichaguri.betterfps.transformers.EventTransformer@406b7d3) returned non-null result: 0
	CoFHCore: -[1.7.10]3.1.4-329
	ThermalFoundation: -[1.7.10]1.2.6-118
	ThermalExpansion: -[1.7.10]4.1.5-248
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	TConstruct Environment: Environment healthy.
	Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
	EnderIO: Found the following problem(s) with your installation:
                  * Optifine is installed. This is NOT supported.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Stencil buffer state: Function set: GL30, pool: forge, bits: 8
	Launched Version: 1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 400 GL version 4.4.0 - Build 20.19.15.4835, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [Transmobifier+v1.0.zip, Blinking Demo, Minecraft+ Resource Pack, [16x16]Vader's+Alternative+Block+Pack+V1.12+For+MC+1.12.zip, Vaders Stacked Items Pack V1.1 For MC 1.11.zip, Smooth Transitions, ItemBound+v1.8.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
	OptiFine Version: OptiFine_1.7.10_HD_U_E3
	Render Distance Chunks: 2
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.4.0 - Build 20.19.15.4835
	OpenGlRenderer: Intel(R) HD Graphics 400
	OpenGlVendor: Intel
	CpuCount: 2

Can I plz have some help?

**Comment by Lance5057** [comment]
This version of minecraft is no longer supported.
