### ISSUE TITLE
Crash when attempting to modify Travellers Gear [1.7.10]

### ISSUE THREAD

**Issue by TheLastSpectre** [Lance5057/Tinkers-Defense#61]
This issue has already been opened and closed, however I am reopening it because it is a glaring issue with the 1.7.10 mod, and the issue was looked at and closed by Lance without comment or resolution. With the 1.7.10 version abandoned, can some other user provide some insight as to how to fix this issue? 

Crash report, in case anyone decides to reply: https://pastebin.com/hXuXnkWj

**Comment by Lance5057** [comment]
1.7.10 is abandon.

**Comment by TheLastSpectre** [comment]
I know it is, I was leaving this open to see if anyone could else could help me find the lines of code to fix this, as I am not yet skilled in Java programming.
