### ISSUE TITLE
[1.7.10]The game breaks when I want to improve the glove of the traveler

### ISSUE THREAD

**Issue by demycat** [Lance5057/Tinkers-Defense#65]
When I want to make an improvement on the rush for the traveler's gloves, then the game is crumbling, how can I fix it?
Minecraft version: 1.7.10
Mod versuion: 1.3.7

**Comment by bba3075** [comment]
The Travelers gear was buggy as hell, best to not use it.

**Comment by demycat** [comment]
@bba3075 Traveller's Gloves normal, if you pump on the rate of extraction

**Comment by bba3075** [comment]
??? What does that even mean. I'm pretty sure mDiyo said that the traveler's stuff was buggy and shouldn't be used.

**Comment by demycat** [comment]
They become buggy only after installation Tinkers Defense
