### ISSUE TITLE
Crash while loading game 1.12.2 mod v1.4.2.17a

### ISSUE THREAD

**Issue by CobaltRealm** [Lance5057/Tinkers-Defense#69]
Crash Report: https://pastebin.com/HccC0Mm9

**Comment by Lance5057** [comment]
Do you have Nihilite disabled?

**Comment by CobaltRealm** [comment]
No, I'll load the game with Nihilite disabled and see what happens

**Comment by kuroyure** [comment]
Im having same issue, How i disable nihilite ?

**Comment by kreezxil** [comment]
Issue:  1.4.2.17a crashes dedicated server Forge 1.12.2 build 2759

Notes:
     NPE while startign server, same issue as 1.4.2.18a

crash report:
https://gist.github.com/483ee514cb74f40f8838df9f175d83a6

fml server latest:
https://gist.github.com/96218b85175d65fbdf7c7738329a8526

**brand new pack and having this issue, tried your 1.4.2.18a first and it was broke too**
