### ISSUE TITLE
NullPointerException for some reason

### ISSUE THREAD

**Issue by zackeezy** [Lance5057/Tinkers-Defense#72]
Crash log: https://pastebin.com/sRCM4FvJ
Version: 1.4.2.18a

**Comment by kreezxil** [comment]
Issue:  1.4.2.18a crashes dedicated server Forge 1.12.2 build 2759

Notes:
     NPE on starting dedicated server

crash report:
https://gist.github.com/29d78208849ee34f033a94ea97372213

fml server latest:
https://gist.github.com/41f3850f167ef9beebb5ca1e271589a3

**Comment by zackeezy** [comment]
I was told by the dev on discord to add nihilite to the material blacklist in the config. That fixed it

**Comment by kreezxil** [comment]
I don't have a mod that adds that material tho.

**Comment by zackeezy** [comment]
I don't either.  That's why it throws a nullpointerexception

**Comment by Lance5057** [comment]
Fixed.
